name: Release Version Checker

on:
    workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  working-directory: "."

defaults:
  run:
    shell: bash

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            VERSION: 0.1.6
            working-directory: .
        steps:
        - name: get nvrs
          run: cargo install nvrs --all-features
        - name: run this awesome software  
          run: nvrs --config ${{ env.working-directory }}/nvrs.toml
        - name: put json output to md
          run: ${{ env.working-directory }}/newver.json > ${{ env.working-directory }}/out.md

        - name: Create Issue From File
          uses: peter-evans/create-issue-from-file@v5
          with:
            title: nvrs Report
            content-filepath: ${{ env.working-directory }}/out.md
            labels: versions, automated issue
            
